$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: DistilBERT Sentiment Training Pipeline
experiment_name: imdb-sentiment-distilbert

inputs:
  dataset_path: 
    type: uri_folder
    path: azureml:imdb-data:1 # Path to dataset in Blob Storage

jobs:
  preprocess:
    type: command
    code: ./src  # Folder with scripts
    command: >-
      python preprocess.py 
      --input_data ${{inputs.dataset_path}} 
      --output_data ${{outputs.preprocessed_data}}
    environment: azureml:distilbert-cpu-env@latest  
    compute: azureml:cpu-instance
    inputs:
      dataset_path: ${{parent.inputs.dataset_path}}
    outputs:
      preprocessed_data:
        type: uri_folder

  train:
    type: command
    code: ./src
    command: >-
      python train_distilbert.py 
      --input_data ${{inputs.preprocessed_data}} 
      --model_output ${{outputs.model_output}}
    environment: azureml:distilbert-gpu-env@latest  # GPU env with Transformers
    compute: azureml:gpu-cluster
    inputs:
      preprocessed_data: ${{parent.jobs.preprocess.outputs.preprocessed_data}}
    outputs:
      model_output:
        type: mlflow_model

  register:
    type: command
    code: ./src
    command: >-
      python register_model.py 
      --model_path ${{inputs.model_output}} 
      --model_name distilbert-sentiment-model
    environment: azureml:distilbert-cpu-env@latest
    compute: azureml:cpu-instance
    inputs:
      model_output: ${{parent.jobs.train.outputs.model_output}}

  deploy:
    type: command
    code: ./src
    command: >-
      python deploy_model.py 
      --model_name distilbert-sentiment-model 
      --endpoint_name distilbert-endpoint 
      --deployment_name distilbert-deployment
    environment: azureml:distilbert-gpu-env@latest
    compute: azureml:gpu-cluster
    inputs:
      model_name: distilbert-sentiment-model
