$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: DistilBERT Sentiment Training Pipeline
experiment_name: imdb-sentiment-distilbert

inputs:
  dataset_path: 
    type: uri_folder
    path: azureml:imdb-data:1 # Path to dataset in Blob Storage

settings:
 default_compute: azureml:serverless

jobs:
  preprocess:
    type: command
    code: ./src  # Folder with scripts
    command: >-
      python preprocess.py 
      --input_data ${{inputs.dataset_path}} 
      --output_data ${{outputs.preprocessed_data}}
    environment: azureml:distilbert-gpu-env@latest  # GPU env with Transformers
    environment_variables:
      AZUREML_ARM_SUBSCRIPTION: ${{parent.inputs.AZUREML_ARM_SUBSCRIPTION}}
      AZUREML_ARM_RESOURCEGROUP: ${{parent.inputs.AZUREML_ARM_RESOURCEGROUP}}
      AZUREML_ARM_WORKSPACE_NAME: ${{parent.inputs.AZUREML_ARM_WORKSPACE_NAME}}
    inputs:
      dataset_path: ${{parent.inputs.dataset_path}}
    outputs:
      preprocessed_data:
        type: uri_folder

  train:
    type: command
    code: ./src
    command: >-
      python train_distilbert.py 
      --input_data ${{inputs.preprocessed_data}} 
      --model_output ${{outputs.model_output}}
    environment: azureml:distilbert-gpu-env@latest  
    environment_variables:
      AZUREML_ARM_SUBSCRIPTION: ${{parent.inputs.AZUREML_ARM_SUBSCRIPTION}}
      AZUREML_ARM_RESOURCEGROUP: ${{parent.inputs.AZUREML_ARM_RESOURCEGROUP}}
      AZUREML_ARM_WORKSPACE_NAME: ${{parent.inputs.AZUREML_ARM_WORKSPACE_NAME}}
    inputs:
      preprocessed_data: ${{parent.jobs.preprocess.outputs.preprocessed_data}}
    outputs:
      model_output:
        type: mlflow_model

  register:
    type: command
    code: ./src
    command: >-
      python register_model.py 
      --model_path ${{inputs.model_output}} 
      --model_name distilbert-sentiment-model
    environment: azureml:distilbert-gpu-env@latest
    environment_variables:
      AZUREML_ARM_SUBSCRIPTION: ${{parent.inputs.AZUREML_ARM_SUBSCRIPTION}}
      AZUREML_ARM_RESOURCEGROUP: ${{parent.inputs.AZUREML_ARM_RESOURCEGROUP}}
      AZUREML_ARM_WORKSPACE_NAME: ${{parent.inputs.AZUREML_ARM_WORKSPACE_NAME}}
    inputs:
      model_output: ${{parent.jobs.train.outputs.model_output}}
