$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: bert-cpu-env
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file:
  name: bert-cpu-env
  channels:
    - conda-forge
  dependencies:
    - python=3.10
    - pip
    - pip:
        - azure-ai-ml
        - azure-identity
        - transformers==4.44.0
        - datasets==2.20.0