name: bert-cpu-env
type: conda
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml
      - azure-identity
      - transformers==4.44.0
      - datasets==2.20.0