$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: bert-gpu-env
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04
conda_file:
  name: bert-gpu-env
  channels:
    - conda-forge
    - pytorch
  dependencies:
    - python=3.10
    - pip
    - pip:
      - torch
      - azure-ai-ml
      - azure-identity
      - scikit-learn
      - transformers
      - datasets
