$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: bert-gpu-env
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.6-cudnn8-ubuntu20.04
conda_file:
  name: bert-gpu-env
  channels:
    - conda-forge
    - pytorch
  dependencies:
    - python=3.10
    - pip
    - 'pytorch::pytorch==2.0.1'
    - 'pytorch::torchaudio'
    - 'pytorch::torchvision'
    - pip:
        - azure-ai-ml
        - azure-identity
        - transformers==4.44.0
        - datasets==2.20.0